images:
- "eu.gcr.io/${PROJECT_ID}/cloud-run/application"
steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "--build-arg" , "PROJECT_ID=${PROJECT_ID}" ,"-t", "eu.gcr.io/${PROJECT_ID}/cloud-run/application:${SHORT_SHA}", "cloud-run/application/"]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "eu.gcr.io/${PROJECT_ID}/cloud-run/application:${SHORT_SHA}"]
- name: 'gcr.io/cloud-builders/gcloud-slim'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    services=(${_SERVICES})
    for service in "${services[@]}"
    do
      gcloud run deploy ${service}-dev --image eu.gcr.io/${PROJECT_ID}/cloud-run/application:${SHORT_SHA} --revision-suffix ${SHORT_SHA} --update-labels stage=dev --region ${_GCP_REGION} --platform managed
    done
substitutions:
  _GCP_REGION: europe-west1
